project:
  type: website
  output-dir: docs

website:
  title: "Ainsley Denham"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - resume.qmd

format:
  html:
    theme: morph
    css: C:/Users/ainsleymarie29/Downloads/bootstrap.min.css
    toc: true
    page-layout: full
editor: visual

